# Generated by Django 4.2.3 on 2023-07-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companyprofile_address_companyprofile_chairman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
